### ISSUE TITLE
User can't dismiss keyboard in login/signup screens

### ISSUE THREAD

**Issue by reesjones** [LecturePulse/ios#1]
Not sure if this is an iOS design feature or a box we have to check in Xcode. If it's possible, the keyboard should be dismissable.

**Comment by justnealpatel** [comment]
I would be willing to see if I can properly solve this.

**Comment by mcsimps2** [comment]
Also to fix, which is related:
Upon entering a username, users should be greeted with a keyboard that has a "next" button in place of the return button to take the user to the password field. Likewise, the password field should have a "Go" button.

This affects the login screen and create an account screen.

The join session view should also adhere to the guidelines mentioned above
